PaddleHQ/paddle-php-sdk

CHANGELOG.md, src/Client.php
Resolves: #3
Any of our resource clients utilising a `null` payload may result in a `"null"` body on the request stream. 
This solution prevents a stream being created on the request if no payload was intended. 
_Note this issue looks like it may only surface when specific HTTP Client/s are used, I've not pinpointed where this happens or which packages would be susceptible_
=> fix: Prevents invalid stream for null payloads

composer.json
In this pull request, php-http/message-factory is removed since it is not used in the library and it is deprecated.
=> Removal of php-http/message-factory

CHANGELOG.md, src/Client.php, src/Entities/Address.php, src/Entities/Business.php, src/Entities/Customer.php, src/Entities/Discount.php, src/Entities/Price.php, src/Entities/Product.php, src/Entities/Shared/ImportMeta.php, src/Entities/Shared/TransactionPayoutTotals.php, src/Entities/Shared/TransactionTotals.php, src/Entities/Subscription.php, src/Entities/TransactionWithIncludes.php, src/Resources/Customers/Operations/ListCustomers.php, src/Resources/Transactions/Operations/List/Includes.php, src/Resources/Transactions/Operations/List/Origin.php, src/Resources/Transactions/Operations/ListTransactions.php, tests/Functional/Resources/Customers/CustomersClientTest.php, tests/Functional/Resources/Notifications/_fixtures/response/list_default.json, tests/Functional/Resources/Subscriptions/_fixtures/response/get_payment_method_change_transaction_entity.json, tests/Functional/Resources/Subscriptions/_fixtures/response/preview_update_full_entity.json, tests/Functional/Resources/Transactions/TransactionsClientTest.php, tests/Functional/Resources/Transactions/_fixtures/response/full_entity.json, tests/Functional/Resources/Transactions/_fixtures/response/full_entity_with_includes.json, tests/Functional/Resources/Transactions/_fixtures/response/list_default.json, tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_one.json, tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_two.json, tests/Functional/Resources/Transactions/_fixtures/response/minimal_entity.json, tests/Functional/Resources/Transactions/_fixtures/response/preview_entity.json
- Added `importMeta` to product, price, address, business, customer, discount and subscription entities
- Added `creditToBalance` to `transaction.details.payoutTotals` and `transaction.details.totals`
- Added `origin` query parameter to list transactions, see [related changelog](https://developer.paddle.com/changelog/2023/filter-transactions-origin?utm_source=dx&utm_medium=paddle-php-sdk).
- Added `available_payment_methods` to transaction with includes entity
- Added `email` query parameter to list customers, see [related changelog](https://developer.paddle.com/changelog/2024/filter-customers-email#filter-customers-by-email-address?utm_source=dx&utm_medium=paddle-php-sdk)
=> Sync API spec with SDK

README.md
Updates the docs for the BC change we made recently.
=> docs: Update README.md for 0.2.0

tests/Functional/Resources/Notifications/NotificationsClientTest.php
Looks like this test was copied from the `to:` version and the parameter wasn't changed to `from:`, you can see the `to:` version above this one
=> Fix list notifications test case in NotificationsClientTest.php

src/Entities/Collections/AdjustmentCollection.php, src/Resources/Adjustments/AdjustmentsClient.php
Fixes an inconsistent naming. 
BREAKING CHANGE: The `AdjustmentsAdjustmentCollection` class is now `AdjustmentCollection`
=> fix!: Use correct naming for AdjusmentCollection

composer.json
CS Fixer recently made some changes that causes us some issues. 
To resolve this at least for now I've pinned to the previous version of CS Fixer. This should be fine as a dev dependency. 
Our pipeline also needs to split out to prevent lint running on multiple version of CS Fixer (configuration may change and become incompatible).
=> fix(deps): Pin CS Fixer to previous version

src/Entities/Report.php, src/Entities/Report/ReportFilter.php, src/Entities/Report/ReportFilterName.php, src/Entities/Report/ReportFilterOperator.php, src/Resources/Reports/Operations/CreateReport.php, tests/Functional/Resources/Reports/ReportsClientTest.php
- ReportFilters -> ReportFilter
- ReportName -> ReportFilterName
- ReportOperator -> ReportFilterOperator
BREAKING CHANGE: Existing usages of the Reports API will fail with class not found. Refactoring to new class names will be required.
=> fix!: Make Report entity naming consistent with SDK

src/Entities/Event/EventTypeName.php, src/Entities/Report/ReportFilterName.php, src/Entities/Shared/TransactionPaymentAttempt.php, src/Resources/Customers/CustomersClient.php, src/Resources/Customers/Operations/ListCreditBalances.php, src/Resources/Notifications/Operations/ListNotifications.php, src/Resources/Subscriptions/Operations/CreateOneTimeCharge.php, src/Resources/Subscriptions/Operations/PreviewOneTimeCharge.php, tests/Functional/Resources/Events/_fixtures/response/list_default.json, tests/Functional/Resources/Notifications/NotificationsClientTest.php, tests/Functional/Resources/Transactions/_fixtures/response/list_default.json, tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_one.json, tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_two.json
- `EventTypeName` enum now supports `customer.imported`
- `ReportFilterName` enum now supports `action`
- Added  `payment_method_id` to Transaction.payments entity and deprecated `stored_payment_method_id`
- List Credit Balances for a Customer now supports filtering by `currency_code`
- Breaking change: ListNotification operation uses same naming conventions as other operations
- Create/Preview a one-time charge for a subscription now supports `receipt_data`
=> Fix!: Sync API Spec

src/Entities/Address.php, src/Entities/Adjustment.php, src/Entities/Business.php, src/Entities/CreditBalance.php, src/Entities/Customer.php, src/Entities/Discount.php, src/Entities/Event.php, src/Entities/EventType.php, src/Entities/Notification.php, src/Entities/Notification/NotificationDiscount.php, src/Entities/Notification/NotificationSubscription.php, src/Entities/NotificationLog.php, src/Entities/NotificationSetting.php, src/Entities/Price.php, src/Entities/PricePreview.php, src/Entities/PricingPreview/PricePreviewDetails.php, src/Entities/PricingPreview/PricePreviewDiscounts.php, src/Entities/PricingPreview/PricePreviewItem.php, src/Entities/PricingPreview/PricePreviewLineItem.php, src/Entities/PricingPreview/PricePreviewTotalsFormatted.php, src/Entities/PricingPreview/PricePreviewUnitTotalsFormatted.php, src/Entities/Product.php, src/Entities/Report.php, src/Entities/ReportCSV.php, src/Entities/Subscription.php, src/Entities/SubscriptionPreview.php, src/Entities/SubscriptionTransaction.php, src/Entities/Transaction.php, src/Entities/TransactionData.php, src/Entities/TransactionPreview.php
Implementors of `\Paddle\SDK\Entities\Entity` should not be used directly. To prevent this the constructors are now private, and the static factory should be used instead conforming to the shape of the API.
A PHPCS rule has been added to automate this and prevent future breakages. 
BREAKING CHANGE: Makes core Entity constructors private.
=> fix!: Make implementors of Entity internal

src/Entities/Adjustment.php, src/Entities/Shared/AdjustmentTotals.php, src/Entities/Subscription/SubscriptionAdjustmentPreview.php
BREAKING CHANGE: Any existing typing for TotalAdjustments will cause  a class not found error until refactored to AdjustmentTotals
=> fix!: Consistent naming for Adjustment totals obj

src/Entities/Subscription/SubscriptionResumeEffectiveFrom.php, src/Resources/Subscriptions/Operations/ResumeSubscription.php, tests/Functional/Resources/Subscriptions/SubscriptionsClientTest.php, tests/Functional/Resources/Subscriptions/_fixtures/request/resume_single_as_enum.json
Fixed:
-  Update resume subscription `effective_from` option to accept RFC 3339 datetime or `immediately`
=> Fix!: Update resume subscription options

src/Entities/NotificationSetting.php, src/Entities/Product.php
Fixed:
- Updated couple of entities that were using collections instead of `array<Entity>`
=> Fix!: Entities should use array instead of collections

src/Entities/Price.php, src/Entities/Subscription/SubscriptionItem.php, src/Notifications/Entities/Price.php, src/Notifications/Entities/Subscription/SubscriptionPrice.php, tests/Functional/Resources/Subscriptions/_fixtures/response/full_entity.json, tests/Functional/Resources/Subscriptions/_fixtures/response/full_entity_with_includes.json, tests/Functional/Resources/Subscriptions/_fixtures/response/list_default.json, tests/Functional/Resources/Subscriptions/_fixtures/response/preview_charge_full_entity.json, tests/Functional/Resources/Subscriptions/_fixtures/response/preview_update_full_entity.json
- Subscription Item uses main Price Entity
- Subscription notification supports new Price fields
BREAKING CHANGE: The class type for a subscription item price property has changed to the main Price entity. Any reliance on the old type will need to be refactored accordingly.
=> fix!: Align subscription price with Price entity

CHANGELOG.md, LICENSE, src/Client.php, src/Entities/Shared/ErrorCode.php
- New error code for payments `declined_not_retryable`, see [related changelog](https://developer.paddle.com/changelog/2024/declined-not-retryable-error-code?utm_source=dx&utm_medium=paddle-php-sdk).
=> Feat: New error code for payments

.github/CODEOWNERS, examples/webhook_verification_PSR7.php
- Created an example of how to validate a webhook when using a framework that does not support PSR-7.
=> Docs: New example of how to verify a webhook when framework does not support PSR7

src/Entities/Discount.php, src/Resources/Discounts/Operations/CreateDiscount.php, src/Resources/Discounts/Operations/UpdateDiscount.php
=> CreateDiscount and UpdateDiscount Ops are missing Custom Data #57

CHANGELOG.md, src/Entities/Subscription/SubscriptionItem.php, src/Notifications/Entities/Subscription/SubscriptionItem.php, tests/Functional/Resources/Events/EventsClientTest.php, tests/Functional/Resources/Events/_fixtures/response/list_default.json, tests/Functional/Resources/Subscriptions/_fixtures/response/full_entity.json, tests/Functional/Resources/Subscriptions/_fixtures/response/full_entity_with_includes.json, tests/Functional/Resources/Subscriptions/_fixtures/response/list_default.json, tests/Functional/Resources/Subscriptions/_fixtures/response/preview_update_full_entity.json
- Added `product` to `subscription.items[]`
=> Feature: Add product to subscription.items

CHANGELOG.md, src/Entities/Transaction.php, tests/Functional/Resources/Subscriptions/SubscriptionsClientTest.php, tests/Functional/Resources/Subscriptions/_fixtures/response/get_payment_method_change_transaction_entity_with_import_meta.json, tests/Functional/Resources/Transactions/TransactionsClientTest.php, tests/Functional/Resources/Transactions/_fixtures/response/full_entity_with_import_meta.json, tests/Functional/Resources/Transactions/_fixtures/response/list_default.json
- Added `import_meta` to `transaction`
=> Feature: Add import_meta to transaction

CHANGELOG.md, src/Notifications/Entities/Subscription/SubscriptionPrice.php, tests/Functional/Resources/Events/EventsClientTest.php, tests/Functional/Resources/Events/_fixtures/response/list_default.json, tests/Functional/Resources/Notifications/_fixtures/response/list_default.json
- Support for `createdAt` and `updatedAt` on Subscription notification prices
=> Feature: Support for createdAt and updatedAt on Subscription notification prices

CHANGELOG.md, src/Entities/Shared/Disposition.php, src/Entities/Subscription/SubscriptionNonCatalogPrice.php, src/Entities/Subscription/SubscriptionNonCatalogPriceWithProduct.php, src/Exceptions/SdkExceptions/InvalidArgumentException.php, src/Resources/NotificationSettings/NotificationSettingsClient.php, src/Resources/NotificationSettings/Operations/ListNotificationSettings.php, src/Resources/PricingPreviews/Operations/PreviewPrice.php, src/Resources/Subscriptions/Operations/PreviewUpdateSubscription.php, src/Resources/Subscriptions/Operations/UpdateSubscription.php, src/Resources/Transactions/Operations/GetTransactionInvoice.php, src/Resources/Transactions/TransactionsClient.php, tests/Functional/Resources/NotificationSettings/NotificationSettingsClientTest.php, tests/Functional/Resources/NotificationSettings/_fixtures/response/list_paginated_page_one.json, tests/Functional/Resources/NotificationSettings/_fixtures/response/list_paginated_page_two.json, tests/Functional/Resources/PricingPreviews/PricingPreviewsClientTest.php, tests/Functional/Resources/Subscriptions/SubscriptionsClientTest.php, tests/Functional/Resources/Subscriptions/_fixtures/request/preview_update_full.json, tests/Functional/Resources/Subscriptions/_fixtures/request/update_full.json, tests/Functional/Resources/Transactions/TransactionsClientTest.php, tests/Unit/Resources/PricingPreviews/Operations/PreviewPriceTest.php
- Support custom prices when updating and previewing subscriptions, see [related changelog](https://developer.paddle.com/changelog/2024/add-custom-items-subscription)
https://github.com/PaddleHQ/paddle-php-sdk/pull/65
- `TransactionsClient::getInvoicePDF` now supports `disposition` parameter, see [related changelog](https://developer.paddle.com/changelog/2024/invoice-pdf-open-in-browser)
https://github.com/PaddleHQ/paddle-php-sdk/pull/68
- Support notification settings pagination, see [related changelog](https://developer.paddle.com/changelog/2024/notification-settings-pagination)
https://github.com/PaddleHQ/paddle-php-sdk/pull/69
- Support notification settings `active` filter
https://github.com/PaddleHQ/paddle-php-sdk/pull/69
- `PreviewPrice` operation no longer allows empty `items` …
=> Feature: API Sync

src/Entities/Shared/TransactionPaymentAttempt.php
The API docs state that the `payment_method_id` can be a `string` or `null` - but the PHP code only expects a string.
The value is `null` when e.g. the payment amount has been reduced to zero by a discount.
=> `payment_method_id` can be `string` or `null`

CHANGELOG.md, src/Entities/Shared/TransactionPaymentAttempt.php, tests/Functional/Resources/Events/_fixtures/response/list_default.json, tests/Functional/Resources/Transactions/TransactionsClientTest.php, tests/Functional/Resources/Transactions/_fixtures/response/full_entity.json, tests/Functional/Resources/Transactions/_fixtures/response/list_default.json
- Test coverage and CHANGELOG for nullable `payment_method_id`
=> fix: Add test coverage and CHANGELOG for nullable `payment_method_id`

CHANGELOG.md, UPGRADING.md, src/Client.php
Changes: https://github.com/PaddleHQ/paddle-php-sdk/compare/v1.1.2...release/v1.2.0
---
- Added `product` to `subscription.items[]`, see [related changelog](https://developer.paddle.com/changelog/2024/subscription-items-product?utm_source=dx&utm_medium=paddle-php-sdk)
- Support for `createdAt` and `updatedAt` on Subscription notification prices
- Support custom prices when updating and previewing subscriptions, see [related changelog](https://developer.paddle.com/changelog/2024/add-custom-items-subscription)
- `TransactionsClient::getInvoicePDF` now supports `disposition` parameter, see [related changelog](https://developer.paddle.com/changelog/2024/invoice-pdf-open-in-browser)
- Support notification settings pagination, see [related …
=> docs(release): v1.2.0

CHANGELOG.md, src/Client.php
With `1.3.0` I forgot to correctly reference this in the client, this patch references the future package release of `1.3.1`
No consumer changes.
=> fix: Reference released version 1.3.1

CHANGELOG.md, src/Client.php
Changes: https://github.com/PaddleHQ/paddle-php-sdk/compare/v1.3.1...docs/release-v1.4.0
---
- Added simulations api [related changelog](https://developer.paddle.com/changelog/2024/webhook-simulator?utm_source=dx&utm_medium=paddle-php-sdk)
- Added `traffic_source` property to `NotificationSetting` entity
- Support notification settings `traffic_source` filter
- Support new payment methods `offline`, `unknown`, `wire_transfer`
- Support `tax_rates_used` property on `Adjustment` entity
- Dropped `receipt_data` on create and preview of a one-time charge for Subscriptions and Transactions
- `TransactionsClient::preview()` `TransactionPreview` response now allows null IDs for non-catalog prices and products:
- `items[]->price` can now return `Price` (with `id`) or `TransactionPreviewPrice` …
=> docs: Release v1.4.0

tests/Functional/Resources/Transactions/TransactionsClientTest.php, tests/Functional/Resources/Transactions/_fixtures/request/create_with_multiple_non_catalog_price_and_product.json, tests/Functional/Resources/Transactions/_fixtures/request/update_with_non_catalog_price_and_product.json
- Correction to transaction create and update tests
=> test: Correction to transaction create and update tests

composer.json
- Use stable Rector version `^1.2`
=> fix: Use stable Rector version

CHANGELOG.md, examples/notification_replay.php, src/Resources/Notifications/NotificationsClient.php, tests/Functional/Resources/Notifications/NotificationsClientTest.php
- `Client->notifications->replay()` now calls the correct endpoint
=> fix: Notification replay now calls correct endpoint

CHANGELOG.md, examples/customer_portal_session.php, src/Client.php, src/Entities/CustomerPortalSession.php, src/Entities/CustomerPortalSession/CustomerPortalSessionGeneralUrl.php, src/Entities/CustomerPortalSession/CustomerPortalSessionSubscriptionUrl.php, src/Entities/CustomerPortalSession/CustomerPortalSessionUrls.php, src/Resources/CustomerPortalSessions/CustomerPortalSessionsClient.php, src/Resources/CustomerPortalSessions/Operations/CreateCustomerPortalSession.php, tests/Functional/Resources/CustomerPortalSessions/CustomerPortalSessionsClientTest.php, tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_empty.json, tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_multiple.json, tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_single.json, tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_empty.json, tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_multiple.json, tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_single.json
- Support for customer portal sessions, see [related changelog](https://developer.paddle.com/changelog/2024/customer-portal-sessions?utm_source=dx&utm_medium=paddle-php-sdk)
- `Client->customerPortalSessions->create()`
=> feat: Add support for customer portal sessions

CHANGELOG.md, src/Client.php, src/Entities/Adjustment.php, src/Entities/Adjustment/AdjustmentType.php, src/Entities/Shared/CurrencyCode.php, src/Notifications/Entities/Adjustment.php, src/Notifications/Entities/Adjustment/AdjustmentType.php, src/Notifications/Entities/Shared/CurrencyCode.php, src/Resources/Adjustments/Operations/CreateAdjustment.php, tests/Functional/Resources/Adjustments/_fixtures/response/full_entity.json, tests/Functional/Resources/Adjustments/_fixtures/response/list_default.json, tests/Functional/Resources/Adjustments/_fixtures/response/minimal_entity.json, tests/Functional/Resources/Simulations/_fixtures/request/adjustment_updated_payload.json, tests/Functional/Resources/Simulations/_fixtures/request/update_full.json, tests/Functional/Resources/Simulations/_fixtures/response/full_entity_adjustment_updated.json
- Support for adjustment type, see [related changelog](https://developer.paddle.com/changelog/2024/refund-credit-full-total?utm_source=dx&utm_medium=paddle-php-sdk)
- Added Vietnamese Dong (`VND`) as a supported currency for payments [related changelog](https://developer.paddle.com/changelog/2024/vietnamese-dong-vnd-supported-currency?utm_source=dx&utm_medium=paddle-php-sdk)
=> Feat: Adding support for adjustment type and VND currency

CHANGELOG.md, src/Client.php, src/Entities/Subscription/SubscriptionDiscount.php, src/Notifications/Entities/Subscription/SubscriptionDiscount.php, tests/Functional/Resources/Subscriptions/_fixtures/response/list_default.json, tests/Unit/Entities/EventTest.php, tests/Unit/Entities/_fixtures/notification/entity/subscription.activated.json, tests/Unit/Entities/_fixtures/notification/entity/subscription.canceled.json
- Subscription discount now supports null `starts_at`
=> fix: Subscription discount now supports null starts_at

CHANGELOG.md, examples/adjustments.php, src/Client.php, src/Resources/Adjustments/Operations/CreateAdjustment.php, tests/Functional/Resources/Adjustments/AdjustmentsClientTest.php, tests/Functional/Resources/Adjustments/_fixtures/request/create_type_full_with_no_items.json, tests/Functional/Resources/Adjustments/_fixtures/request/create_type_full_with_null_items.json, tests/Functional/Resources/Adjustments/_fixtures/request/create_type_partial_with_items.json, tests/Unit/Resources/Adjustments/Operations/CreateAdjustmentTest.php
- Adjustment items can be omitted for when adjustment type is full
=> fix: Adjustment items can be omitted when adjustment type is full

CHANGELOG.md, examples/transaction_revision.php, src/Entities/Event.php, src/Entities/Event/EventTypeName.php, src/Entities/Transaction.php, src/Notifications/Entities/Transaction.php, src/Notifications/Events/TransactionRevised.php, src/Resources/Transactions/Operations/Revise/TransactionReviseAddress.php, src/Resources/Transactions/Operations/Revise/TransactionReviseBusiness.php, src/Resources/Transactions/Operations/Revise/TransactionReviseCustomer.php, src/Resources/Transactions/Operations/ReviseTransaction.php, src/Resources/Transactions/TransactionsClient.php, tests/Functional/Resources/EventTypes/_fixtures/response/list_default.json, tests/Functional/Resources/Notifications/NotificationsClientTest.php, tests/Functional/Resources/Notifications/_fixtures/response/list_default.json, tests/Functional/Resources/SimulationTypes/_fixtures/response/list_default.json, tests/Functional/Resources/Transactions/TransactionsClientTest.php, tests/Functional/Resources/Transactions/_fixtures/request/revise_basic.json, tests/Functional/Resources/Transactions/_fixtures/request/revise_customer.json, tests/Functional/Resources/Transactions/_fixtures/request/revise_full.json, tests/Functional/Resources/Transactions/_fixtures/response/full_entity.json, tests/Functional/Resources/Transactions/_fixtures/response/full_entity_with_includes.json, tests/Functional/Resources/Transactions/_fixtures/response/list_default.json, tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_one.json, tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_two.json, tests/Functional/Resources/Transactions/_fixtures/response/minimal_entity.json, tests/Unit/Entities/EventTest.php, tests/Unit/Entities/_fixtures/notification/entity/transaction.revised.json
- Added `transactions.revise` operation to revise a transaction and added `revised_at` to `Transaction` entity, see [related changelog](https://developer.paddle.com/changelog/2024/revise-transaction-customer-information?utm_source=dx&utm_medium=paddle-php-sdk).
- Added support for `transaction.revised` notification, see [related changelog](https://developer.paddle.com/changelog/2024/revise-transaction-customer-information?utm_source=dx&utm_medium=paddle-php-sdk).
- Handle known entity types for events that are not supported by the current SDK version. `UndefinedEvent` will always return an `UndefinedEntity`.
=> feat: Support transaction revisions

src/Entities/Shared/TransactionPaymentAttempt.php
Hey everyone,
I've been noticing a ton of errors over the past few months affecting some of my customers.
`Warning: Undefined array key "stored_payment_method_id" in Paddle\SDK\Entities\Shared\TransactionPaymentAttempt::from at line 39`
This happens when I use the `getPaymentMethodChangeTransaction` method to retrieve the transaction ID in order to update the credit card in my billing dashboard.
Could the SDK be outdated compared to the API?
I've implemented a temporary fix—please review it. This issue has already cost me significant revenue and customer churn.
Thanks,  
Ben
=> fix: undefined array key error on stored_payment_method_id

CHANGELOG.md, README.md, src/Exceptions/ApiError.php, src/ResponseParser.php, tests/Unit/ResponseParserTest.php
- `ApiError` will now have `retryAfter` property set for [too_many_requests](https://developer.paddle.com/errors/shared/too_many_requests) errors
=> feat: Add `retryAfter` property to `ApiError`

CHANGELOG.md, src/Resources/Transactions/Operations/CreateTransaction.php, src/Resources/Transactions/Operations/Discount/TransactionNonCatalogDiscount.php, src/Resources/Transactions/Operations/PreviewTransaction.php, src/Resources/Transactions/Operations/UpdateTransaction.php, tests/Functional/Resources/Transactions/TransactionsClientTest.php, tests/Functional/Resources/Transactions/_fixtures/request/create_with_noncatalog_discount_full.json, tests/Functional/Resources/Transactions/_fixtures/request/create_with_noncatalog_discount_minimal.json, tests/Functional/Resources/Transactions/_fixtures/request/preview_with_noncatalog_discount_full.json, tests/Functional/Resources/Transactions/_fixtures/request/preview_with_noncatalog_discount_minimal.json, tests/Functional/Resources/Transactions/_fixtures/request/update_with_noncatalog_discount_full.json, tests/Functional/Resources/Transactions/_fixtures/request/update_with_noncatalog_discount_minimal.json
- Non-catalog discounts on Transactions, see [changelog](https://developer.paddle.com/changelog/2025/custom-discounts?utm_source=dx&utm_medium=paddle-php-sdk)
=> feat: Add support for non-catalog discounts
